language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

notifications:
  email: false

sudo: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script: ./gradlew build test